from typing import List

from sqlmodel import Field, SQLModel, Relationship


class FarmBase(SQLModel):# clint can access it
    name : str = Field(index=True)
    productivity: float = Field(default=0.0, index=True)


class Farm(FarmBase, table=True): # this is the ORM model and not Accessible by the clint
    id: int | None =  Field(default=None, primary_key=True)
    # Relationship to Crop
    crops: List["Crop"] = Relationship(back_populates="farm")
    # Relationship to Sensor
    sensors: List["Sensor"] = Relationship(back_populates="farm")


class FarmPublic(FarmBase):# clint can access it
    id: int


class FarmCreate(FarmBase):#this for creating new farm the id will be generated by DB
    pass


class FarmUpdate(FarmBase):
    name: str | None = None
    productivity: float | None = None